x-default-environment: &default_env
  TZ: &default_TZ "Europe/Nicosia"
  performance_cores: &default_performance_cores ${CORES_PRIMARY:-}
  efficiency_cores: &default_efficiency_cores ${CORES_SECONDARY:-}

services:
  wrk2:
    profiles: ["RAIN_FIRE"]
    image: wrk2:latest
    build:
      context: ../utils/wrk2
      dockerfile: Dockerfile
    container_name: wrk2
    volumes:
      - ../results/benchmarks:/usr/local/bin/benchmarks
    environment:
      TZ: *default_TZ
      WRK_HOST: ${WRK_HOST}
      WRK_PORT: 8080
      WRK_ENDPOINT: ${WRK_ENDPOINT}
      WRK_THREADS: ${WRK_THREADS}
      WRK_CONNECTIONS: ${WRK_CONNECTIONS}
      WRK_DURATION: ${WRK_DURATION}
      WRK_RATE: ${WRK_RATE}
      WRK_SLEEP_BETWEEN: ${WRK_SLEEP_BETWEEN}
      WRK_SLEEP_INIT: ${WRK_SLEEP_INIT}
    restart: no
    pull_policy: never
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 64M
    cpuset: *default_performance_cores
    command: ["/bin/sh", "-c", "sleep ${WRK_SLEEP_INIT} && /usr/local/bin/run.sh && tail -f /dev/null"]