source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"
gem "webrick", "~> 1.9.2"
gem "logger", "~> 1.6.0"
gem "wdm", "~> 0.2.0", platforms: [:mingw, :x64_mingw, :mswin]

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
end
